Repository DIT112-V21/group-12, pull requests merged in 2021-05, with the labels that each got.

#46 Android build CI
  .github/workflows/android-build.yml
  Application/build.gradle
  Application/src/main/res/layout/activity_new_moves.xml
  gradlew
Labels: Sprint #4, Task

#49 Update activity_new_moves.xml
  Application/src/main/res/layout/activity_new_moves.xml
Labels: bug

#47 Update README.md
  README.md
Labels: Task

#50 Dance moves
  .idea/runConfigurations.xml
  Application/src/main/AndroidManifest.xml
  Application/src/main/java/com/example/android/dancecar/Choreography.java
  Application/src/main/java/com/example/android/dancecar/CreatedDanceMove.java
  Application/src/main/java/com/example/android/dancecar/DBHelper.java
  Application/src/main/java/com/example/android/dancecar/DanceMove.java
  Application/src/main/java/com/example/android/dancecar/DancingActivity.java
  Application/src/main/java/com/example/android/dancecar/DrivingActivity.java
  Application/src/main/java/com/example/android/dancecar/IndividualMove.java
  Application/src/main/java/com/example/android/dancecar/RecordDanceMoveActivity.java
  Application/src/main/res/layout/activity_dancing.xml
  Application/src/main/res/layout/activity_driving.xml
  Application/src/main/res/layout/activity_record_dance_move.xml
  arduino/smartcar/smartcar.ino
  screenshots/dark_1_welcome.png
  screenshots/dark_3_settings.png
  screenshots/dark_4_theme_options.png
  screenshots/light_1_welcome.png
  screenshots/light_2_preferences.png
  screenshots/light_3_settings.png
  screenshots/light_4_theme_options.png
  screenshots/smart_dark_2_preferences.png
Labels: Sprint #4

#51 Update README.md
  README.md
Labels: Task

#53 Update README.md
  README.md
Labels: Sprint #4

#54 #43 Refactors code
  Application/src/main/AndroidManifest.xml
  Application/src/main/java/com/example/android/dancecar/Activities/DancingActivity.java
  Application/src/main/java/com/example/android/dancecar/Activities/DrivingActivity.java
  Application/src/main/java/com/example/android/dancecar/Activities/RecordDanceMoveActivity.java
  Application/src/main/java/com/example/android/dancecar/Connections/DBHelper.java
  Application/src/main/java/com/example/android/dancecar/Connections/MqttClient.java
  Application/src/main/java/com/example/android/dancecar/Mode.java
  Application/src/main/java/com/example/android/dancecar/Moves/Choreography.java
  Application/src/main/java/com/example/android/dancecar/Moves/CreatedDanceMove.java
  Application/src/main/java/com/example/android/dancecar/Moves/DanceMove.java
  Application/src/main/java/com/example/android/dancecar/Moves/IndividualMove.java
  Application/src/main/res/layout/activity_dancing.xml
Labels: Sprint #4, Task

#55 Update README.md
  README.md
Labels: Task, documentation
