Repository DIT112-V21/group-12, pull requests merged in 2021-04, with the labels that each got.

#9 Add basic steering functions
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User story

#10 Change velocity of car
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User story

#12 Basic car movements
  .vscode/launch.json
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User story

#15 Steering modes
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User story

#14 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#26 #24 Add MQTT connection
  .github/workflows/arduino-build.yml
  arduino/smartcar/smartcar.ino
Labels: Sprint #2, Task, completed

#29 Update README.md
  README.md
Labels: documentation
